---

- hosts: all:!removed
  name: configure users
  become: yes
  roles:
    - { role: users_configured }
    - { role: local_ssh_configured }
    - { role: staging }
  tags:
    - users








...
