---

- hosts: all
  become: yes
  tasks:
    - name: Update packages list
      apt: update_cache=yes
      when: (ansible_os_family == 'Debian' and not 'proxmox' in group_names)

    - name: List packages to upgrade (1/2)
      shell: aptitude -q -F%p --disable-columns search "~U"
      changed_when: False
      failed_when: False
      when: (ansible_os_family == 'Debian')
      register: updates

    - name: List packages to upgrade (2/2)
      debug: msg="{{ updates.stdout_lines | count }} packages to upgrade ({{ updates.stdout_lines | join(', ') }})"
      failed_when: False
      when: (ansible_os_family == 'Debian' and not 'proxmox' in group_names and updates.stdout_lines )

    - name: Upgrade packages
      apt: upgrade=safe
      when: (ansible_os_family == 'Debian' and not 'proxmox' in group_names)

    - name: Check what the new version is
      shell:  lsb_release -r | awk '{print $2}'
      changed_when: False
      register: new_release
      when: not 'proxmox' in group_names

    - name: Notify distribution version upgrade
      debug: msg="Debian has been upgraded from {{ ansible_lsb.release }} to {{ new_release.stdout }}"
      when: (not 'proxmox' in group_names and ansible_lsb.release != new_release.stdout)

    - name: List services to restart (1/2)
      shell: checkrestart | grep ^service | awk '{print $2}'
      register: services
      changed_when: False
      when: (ansible_os_family == 'Debian' and not 'proxmox' in group_names)

    - name: List services to restart (2/2)
      debug: msg="{{ services.stdout_lines | count }} services to restart ({{ services.stdout_lines | join (', ') }})"
      when: (ansible_os_family == 'Debian' and not 'proxmox' in group_names and services.stdout_lines)

