---
- hosts: localhost
  name: "Configure user local SSH"
  pre_tasks:
    - name: Check for single host
      fail: msg="This playbook must be ran without inventory and without hosts ':' ansible-playbook ./generate_local_ssh_config.yml --inventory=/dev/null"
      when: ( play_hosts | length ) != 1

    - name: "Check for localhost play"
      fail: msg="This playbook must be ran without inventory and without hosts ':' ansible-playbook ./generate_local_ssh_config.yml --inventory=/dev/null"
      when: inventory_hostname != "localhost"

  roles:
    - { role: local_ssh_configured }
...
